### ISSUE TITLE
Output loading order

### ISSUE THREAD

**Issue by jnyrup** [mhelvens/latex-pkgloader#5]
It would be nice to be able to output the loading order of packages to the document or an external file. This way one could avoid to so sort the packages on each run.

**Comment by vermiculus** [comment]
This would require some sort of determination on the collection of packages we're trying to load. If the packages change, we need to re-calculate the changes.

**Comment by mhelvens** [comment]
@jnyrup: Are talking about doing some caching in the background? @vermiculus makes a good argument against this idea: When should pkgloader invalidate the cache and re-calculate loading order? When you change your configuration, when you update pkgloader, etc. It's hard to figure this out from a LaTeX package.

But even if it can be done, would it be worth the extra complexity? The time used to calculate the loading order on the fly should be negligible. Does it take up a lot of time in your runs?

**Comment by vermiculus** [comment]
perhaps some general benchmarking is due here.

**Comment by mhelvens** [comment]
If you'd like to do that, awesome. But some educated guesswork may suffice. pkgloader maintains a graph, and does the following with it:

* It adds a vertex for every package it knows about (linear complexity).
* It adds an edge for every rule it knows about (linear complexity).
* It constructs a transitive closure (polynomial complexity).
* It maps the resulting partial loading order onto the requested packages, and the packages that are pulled in (linear complexity).
* It loads these packages in topological order (linear complexity).

We're talking about ~30 packages right now, and a similar number of rules. Let's say 50 for both.

All linear operations are negligible. Constructing the transitive closure is the most expensive operation, which currently uses the [Floyd-Warshall algorithm](https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm), with a complexity of V³ = 50³ = 125k operations.

I'd be surprised if this takes over 100ms on a modern computer. If you think I'm wrong, let me know.

**Comment by jnyrup** [comment]
Sorry for the incomplete description, I wasn't thinking of any caching feature. As you both mention, when to invalidate the cache?

My idea was if pkgloader could output resolved package order conflicts. This way users (who likes to learn) can know if their manually typed loading order has problems.
This could be controlled via a package option {silent, warn, error}, where silent would be the default value.

**Comment by vermiculus** [comment]
While it'd be nice to have such a 'corrective' mode, I'm not sure Floyd–Warshall can be adapted to suit that.

**Comment by mhelvens** [comment]
Hm. This has little to do with the transitive closure algorithm. Rather, it will just take time to program, and the payoff seems minimal. (Also, sadly, I don't have much LaTeX time these days.)

So anyone is more than welcome to implement this and send in a pull request. But I don't see this feature being high on my list of priorities for the foreseeable future.
