### ISSUE TITLE
Cannot load pkgloader

### ISSUE THREAD

**Issue by jnyrup** [mhelvens/latex-pkgloader#6]
Trying to typeset the following throws multiple errors.
```
\RequirePackage{pkgloader}
\documentclass{article}
\usepackage{algorithm}
\usepackage{hyperref}
\usepackage{float}
\LoadPackagesNow
\begin{document}
\end{document}
```
Here is the [log](http://pastebin.com/kaQjShQD).

**Comment by mhelvens** [comment]
Right. This is, in fact, a bug in the `withargs` package. It uses the `\int_case:nnn` function, which was removed in a recent update of `expl3`. The function is now called `int_case:nnF`. As a quick fix, if you replace the function name in `withargs.sty`, it should fix things. (Alternatively, use an earlier version of `expl3`.)

I'll try to get out a fixed version as soon as possible, but it may have to wait a week or so. In the meantime, I'd like to hear if the above fix works for you.

Thanks!

**Comment by jnyrup** [comment]
Patching `withargs.sty` solves the problem.

Thanks!

**Comment by mhelvens** [comment]
Good to hear. But `withargs` is also a package of mine, so I still need to fix it. ;-)
