### ISSUE TITLE
Add `ExecuteAfterPackageLoaded` environment.

### ISSUE THREAD

**Issue by koppor** [mhelvens/latex-pkgloader#8]
In our [computer science template](https://github.com/latextemplates/uni-stuttgart-computer-science-template/blob/template/preambel/packages_and_options.tex), we not only load packages, but also configure them after loading.

Example:

``` latex
%for theorems, replacement for amsthm
\usepackage[amsmath,hyperref]{ntheorem}
\theorempreskipamount 2ex plus1ex minus0.5ex
\theorempostskipamount 2ex plus1ex minus0.5ex
\theoremstyle{break}
\newtheorem{definition}{Definition}[section]
```

When directly using `\RequirePackage{pkgloader}`, these commands fail as the package does not get loaded immediatly.

One possiblity is to use `\LoadPackagesNow` and issue all configurations afterwards. The drawback is that the `usepackage` commands and the configurations are then split away. My goal is to keep them together.

Therefore, I'd like to have a `\ExecuteAfterPackageLoaded` environment, which executes the nested commands directly after the given package is loaded.

Example:

``` latex
\begin{ExecuteAfterPackageLoaded}[ntheroem]
\theorempreskipamount 2ex plus1ex minus0.5ex
\theorempostskipamount 2ex plus1ex minus0.5ex
\theoremstyle{break}
\newtheorem{definition}{Definition}[section]
\end{ExecuteAfterPackageLoaded}
```

**Comment by vermiculus** [comment]
Check out [`afterpackage`](https://www.ctan.org/pkg/afterpackage).

**Comment by koppor** [comment]
Thank you for the pointer. Maybe, you could include that in the documentation? That will help users not knowing all packages :innocent:

Some code snippets are just copy and paste from the internet... There are so many things going wrong out there.

![duty calls](https://imgs.xkcd.com/comics/duty_calls.png)
<https://xkcd.com/386/>

**Comment by vermiculus** [comment]
Well, we'll have to leave the decision of what to add to the package or its documentation to @mhelvens 😄

"So many things going wrong out there" – you're telling me… It's a major problem we're trying to address as a community: see [johannesbottcher/templateConfusion](https://github.com/johannesbottcher/templateConfusion).

**Comment by mhelvens** [comment]
Hi guys! Yes, `afterpackage` could be used for this. But `pkgloader` itself can be used for this as well:

```latex
\RequirePackage {pkgloader}
    \usepackage[amsmath,hyperref]{ntheorem}
    \begin{filecontents}{ntheorem-config.sty}
        \theorempreskipamount 2ex plus1ex minus0.5ex
        \theorempostskipamount 2ex plus1ex minus0.5ex
        \theoremstyle{break}
        \newtheorem{definition}{Definition}[section]
    \end{filecontents}
    \Load {ntheorem-config} always after {ntheorem}
\LoadPackagesNow
```

Sure, there is the downside of having to come up with a redundant file name, but this is still conceptually more elegant, because your configuration code now has its own place in the dependency graph, and will be treated as such.

Would you try this and let me know if it works? I'm not in a good position to test it myself at the moment.

**Comment by vermiculus** [comment]
That's super clever.
